global:
  scrape_interval: 60s

#remote_write:
#  - url: https://prometheus-prod-13-prod-us-east-0.grafana.net/api/prom/push
#    basic_auth:
#      username: <>
#      password: <>
scrape_configs:
  - job_name: node
    static_configs:
      - targets: ["localhost:8090"]
  - job_name: my-actuator
    metrics_path: "/actuator/prometheus"
    scrape_interval: 20s
    static_configs:
      - targets: ["host.docker.internal:8090"]
        labels:
          group: "testing"